import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Contacts.module.css'
import Link from 'next/link'
import { getEmailHref, getPhoneHref, onCopyStyle, offCopyStyle } from '../util'
import copyIcon from '../public/icons/copy.svg'
import phoneIcon from '../public/icons/phone.svg'
import emailIcon from '../public/icons/envelope-alt.svg'
import { useState, useEffect } from 'react'

export async function getStaticProps() {
  const res = await fetch(`https://jsonplaceholder.typicode.com/users`)
  const contactData = await res.json()

  if (!contactData) {
    return {
      notFound: true,
    }
  }
  return {
    props: { contactData }
  }
}

export default function Contacts({ contactData }) {

  const [copy, setCopy] = useState(false)
  const handleCopy = (copiedItem) => {
    if (window.isSecureContext) {
      navigator.clipboard.writeText(copiedItem);
    }
    setCopy(true)
  }
  useEffect(() => {
    setTimeout(() => {
      setCopy(false)
    }, 10000);
  }, [copy])
  return (
    <div className={styles.container}>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Browse your contacts
        </h1>

        <p className={styles.description}>
          Click on any name to view more details about it{' '}
        </p>

        <div className={styles.grid}>
          {contactData.map((contact) => (
            <li key={contact.id} className={styles.card}>
              <Link
                href={`/contacts/${contact.id}`}
              >
                <h2>{contact.name}</h2>
              </Link>
              <p className={styles.city}>from {contact.address.city}</p>
              <br />
              <div className={styles.briefDetailsWrapper}>
                <span className={styles.briefDetails}>
                  <Image src={phoneIcon} height={20} />
                  <a href={getPhoneHref(contact.phone)}>:&nbsp;{contact.phone}</a>
                  <Image src={copyIcon} className={styles.copyButton} onClick={() => handleCopy(contact.phone)} height={20} />
                </span>
                <span className={styles.briefDetails}>
                  <Image src={emailIcon} height={20} />
                  <a href={getEmailHref(contact.email)}>:&nbsp;{contact.email}</a>
                  <Image src={copyIcon} className={styles.copyButton} onClick={() => handleCopy(contact.email)} height={20} />
                </span>
              </div>
            </li>
          ))}
        </div>
      </main>
      <p style={copy ? onCopyStyle : offCopyStyle}>copied ☑</p>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
