import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Contacts.module.css'
import Link from 'next/link'

export async function getStaticProps() {
  const res = await fetch(`https://jsonplaceholder.typicode.com/users`)
  const contactData = await res.json()

  if (!contactData) {
    return {
      notFound: true,
    }
  }
  return {
    props: { contactData }
  }
}

export default function Contacts({ contactData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Browse your contacts
        </h1>

        <p className={styles.description}>
          Click on any contact to view more details about it{' '}
        </p>

        <div className={styles.grid}>
          {contactData.map((contact) => (
            <Link
              key={contact.id}
              href={`/contacts/${contact.id}`}
            >
              <li className={styles.card}>
                <h2>{contact.name}</h2>
                <p className={styles.city}>from {contact.address.city}</p>
                <br />
                <a>{contact.phone}</a>

              </li>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
